RUN_STRINGS = (
    "Ahora me ves, ahora no." "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Regresa aquí!",
    "GAAAAAAAAAAAAAAAA!!!!!!!",
    "Cuidado con la pared!",
    "No me dejes solo con ellos!!",
    "Tienes compañía!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Oye, hazte responsable de lo que acabas de hacer.!",
    "Que las probabilidades estén siempre a tu favor.",
    "Corran todos, acaban de lanzar una bomba 💣💣",
    "Y ellos desaparecieron para siempre, para nunca más ser vistos.",
    "La leyenda lo tiene, todavía están corriendo.",
    "Hasta la vista, baby.",
    "Ah, qué desperdicio. me gusto ese.",
    "Como diría el Doctor ... CORRE!",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_FALLEN_TEMPLATES = (
    "Abofetéame una vez más y te silenciaré.",
    "Deja de abofetearme 😡",
    [
        "Te estoy silenciando por un minuto.",  # normal reply
        "Deja de abofetearme, solo porque no puedo silenciarte 😡",  # reply to admin
        "tmute",  # command
        "Callate la boca!",
        "Silencio!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} fue asesinad@ por magia.",
    "{user2} está hambrient@ sin palmaditas.",
    "{user2} fue arrojado al vacío por {user1}.",
    "{user2} se desmayó.",
    "{user2} se ha quedado sin pokemon utilizables! {user2} Se desmayó!",
    "{user2} amenazó a {user2} con una cuchara!",
    "{user2} got rekt.",
    "La cabeza de {user2} fue divida en 2 por {user1}.",
    "{user2} Fue cortad@ y repartid@ en cubitos por {user1}.",
    "{user2} juega cod de una manera manca 🤬.",
    "{user2} Fue apuñalado por {user1}.",
    "{user2} comió una granada.",
    "{user2} es lo que hay para cenar!",
    "{user2} fue rescindido por {user1}.",
    "{user1} spammeó a {user2} con Noporn.",
    "{user1} hackeó el instagram de {user2} ahora está expuest@!!",
    "{user1} puso {user2} en la friendzone.",
    "{user1} golpeó a {user2} con una cuchara!",
    "{user2} recibió una llamada del Doctor {user1}.",
    "{user1} decapitó a {user2}.",
    "{user2} fue aplastad@ ... por una turba enojada.",
    "{user1} le sacó los pantalones a {user2}.",
    "{user2} fue KO de un golpe por {user1}.",
    "{user1} madreó a {user2} y le formateó el cerebro.",
    "{user2} fue un error. - '{user1}' ",
    "{user2} fue despedido.",
    "{user1} {hits} {user2} con un bate!.",
    "{user1} {hits} {user2} con una patada de Taijutsu!.",
    "{user1} {hits} {user2} con guantes X!.",
    "{user1} {hits} {user2} con un Jet Punch!.",
    "{user1} {hits} {user2} con una pistola de chorro!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Golpes consecutivos a {user2}*.",
    "*Golpes normales a {user2}*.",
    "*Picar los ojos a {user2}*.",
    "*Coñazo a {user2}*.",
    "*Ignora a {user2} para dejarlo morir de vergüenza*.",
    "*Apunta a {user2}* ¿Qué pasa con este atrevido ... niñ@ atrevid@?.",
    "*Golpea a {user2} con un tornado de fuego*.",
    "{user1} pincha a {user2} en la espalda!",
    "{user1} pincha a {user2} en el abdomen!",
    "{user1} pincha {user2}!",
    "{user1} pincha {user2} con una aguja!",
    "{user1} pincha {user2} con una pluma!",
    "{user1} pincha {user2} con una pistola eléctrica!",
    "{user2} es secretamente un Furry!",
    "¡Hola a todos! {user1} me pide que sea malo!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Toma esto {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Aquí {user2} espera esto\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nMuereeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Insecticida a {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} Apestas!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} con {item}.",
    "{user1} {hits} {user2} en la cara con {item}.",
    "{user1} {hits} {user2} un poco con un {item}.",
    "{user1} {throws} con {item} a {user2}.",
    "{user1} agarra un {item} y lo {throws} a la cara de {user2} ",
    "{user1} lanza un {item} en la dirección general de {user2} ",
    "{user1} comienza a abofetear a {user2} con un {item}.",
    "{user1} fija a {user2} y lo {hits} repetidamente con un {item}.",
    "{user1} gagarra un {item} y {hits} a {user2} con eso.",
    "{user1} ata a {user2} a una silla y {throws} un {item} hacia ellos.",
    "{user1} dio un empujón amistoso para ayudar a {user2} para aprender a nadar en la lava.",
    "{user1} intimidó a {user2}.",
    "Nyaan se comió la pierna de {user2}. *nomnomnom*",
    "{user1} {throws} una bola maestra a {user2},  la resistencia es inútil.",
    "{user1} golpea a {user2} con un rayo de acción...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} golpes a {user2} con {item}.",
    "Ronda 2!..Listos? ... PELEEN!!",
    "Buzz Lightyear lanzará a {user2} al infinito y más allá.",
    "{user2} comió un murciélago y descubrió una nueva enfermedad.",
    "{user1} dobló a {user2} en un avión de papel",
    "{user1} le sirvió a {user2} un poco de sopa de murciélago.",
    "{user2} fue enviado a su hogar, el planeta de los simios.",
    "{user1} echó a {user2} de un tren en movimiento.",
    "{user2} acaba de matar al perro de John Wick.",
    "{user1} realizó un hechizo Avada Kadavra en {user2}.",
    "{user1} sometió a {user2} a un horno de fuego.",
    "Sakura Haruno acaba de volverse más útil que {user2}.",
    "{user1} desconectó el soporte vital de {user2}.",
    "{user1} subscribió a {user2} a 5 años de mala conexión a Internet..",
    "¿Sabes qué es peor que las bromas de papá? {user2}!",
    "{user1} tomó todas las galletas de {user2}.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} perdió su pieza de carrera!",  # No game no life reference
    "Cállate {user2}, sólo eres {user2}.",  # No game no life reference
    "{user1} golpea a {user2} con Aka si anse!",  # No game no life reference
    "@NeoTheKitty araña a {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu se come a {user2}",  # Dbz
    "Goblin slayer mata a {user2}",  # Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = ("ɪ ᴀᴍ ᴀʟɪᴠᴇ ʙᴀʙʏ! 🖤",)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 As I see it, yes.",
    "🟡 Ask again later.",
    "🟡 Better not tell you now.",
    "🟡 Cannot predict now.",
    "🟡 Concentrate and ask again.",
    "🟡 Don’t count on it.",
    "🟢 It is certain.",
    "🟢 It is decidedly so.",
    "🟢 Most likely.",
    "🔴 My reply is no.",
    "🔴 My sources say no.",
    "🔴 Outlook not so good.",
    "🟢 Outlook good.",
    "🟡 Reply hazy, try again.",
    "🟢 Signs point to yes.",
    "🔴 Very doubtful.",
    "🟢 Without a doubt.",
    "🟢 Yes.",
    "🟢 Yes – definitely.",
    "🟢 You may rely on it.",
]

DECIDE = ("Yes.", "No.", "Maybe.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables.",
)
