RUN_STRINGS = (
    "Ahora me ves, ahora no." "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Regresa aquí!",
    "GAAAAAAAAAAAAAAAA!!!!!!!",
    "Cuidado con la pared!",
    "No me dejes solo con ellos!!",
    "Tienes compañía!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Oye, hazte responsable de lo que acabas de hacer.!",
    "Que las probabilidades estén siempre a tu favor.",
    "Corran todos, acaban de lanzar una bomba 💣💣",
    "Y ellos desaparecieron para siempre, para nunca más ser vistos.",
    "La leyenda lo tiene, todavía están corriendo.",
    "Hasta la vista, baby.",
    "Ah, qué desperdicio. me gusto ese.",
    "Como diría el Doctor ... CORRE!",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_FALLEN_TEMPLATES = (
    "Abofetéame una vez más y te silenciaré.",
    "Deja de abofetearme 😡",
    [
        "Te estoy silenciando por un minuto.",  # normal reply
        "Deja de abofetearme, solo porque no puedo silenciarte 😡",  # reply to admin
        "tmute",  # command
        "Callate la boca!",
        "Silencio!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} fue asesinad@ por magia.",
    "{user2} está hambrient@ sin palmaditas.",
    "{user2} fue arrojado al vacío por {user1}.",
    "{user2} se desmayó.",
    "{user2} se ha quedado sin pokemon utilizables! {user2} Se desmayó!",
    "{user2} amenazó a {user2} con una cuchara!",
    "{user2} got rekt.",
    "La cabeza de {user2} fue divida en 2 por {user1}.",
    "{user2} Fue cortad@ y repartid@ en cubitos por {user1}.",
    "{user2} juega cod de una manera manca 🤬.",
    "{user2} Fue apuñalado por {user1}.",
    "{user2} comió una granada.",
    "{user2} es lo que hay para cenar!",
    "{user2} fue rescindido por {user1}.",
    "{user1} spammeó a {user2} con Noporn.",
    "{user1} hackeó el instagram de {user2} ahora está expuest@!!",
    "{user1} puso {user2} en la friendzone.",
    "{user1} golpeó a {user2} con una cuchara!",
    "{user2} recibió una llamada del Doctor {user1}.",
    "{user1} decapitó a {user2}.",
    "{user2} fue aplastad@ ... por una turba enojada.",
    "{user1} le sacó los pantalones a {user2}.",
    "{user2} fue KO de un golpe por {user1}.",
    "{user1} madreó a {user2} y le formateó el cerebro.",
    "{user2} fue un error. - '{user1}' ",
    "{user2} fue despedido.",
    "{user1} {hits} {user2} con un bate!.",
    "{user1} {hits} {user2} con una patada de Taijutsu!.",
    "{user1} {hits} {user2} con guantes X!.",
    "{user1} {hits} {user2} con un Jet Punch!.",
    "{user1} {hits} {user2} con una pistola de chorro!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Golpes consecutivos a {user2}*.",
    "*Golpes normales a {user2}*.",
    "*Picar los ojos a {user2}*.",
    "*Coñazo a {user2}*.",
    "*Ignora a {user2} para dejarlo morir de vergüenza*.",
    "*Apunta a {user2}* ¿Qué pasa con este atrevido ... niñ@ atrevid@?.",
    "*Golpea a {user2} con un tornado de fuego*.",
    "{user1} pincha a {user2} en la espalda!",
    "{user1} pincha a {user2} en el abdomen!",
    "{user1} pincha {user2}!",
    "{user1} pincha {user2} con una aguja!",
    "{user1} pincha {user2} con una pluma!",
    "{user1} pincha {user2} con una pistola eléctrica!",
    "{user2} es secretamente un Furry!",
    "¡Hola a todos! {user1} me pide que sea malo!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Toma esto {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Aquí {user2} espera esto\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nMuereeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Insecticida a {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} Apestas!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} con {item}.",
    "{user1} {hits} {user2} en la cara con {item}.",
    "{user1} {hits} {user2} un poco con un {item}.",
    "{user1} {throws} con {item} a {user2}.",
    "{user1} agarra un {item} y lo {throws} a la cara de {user2} ",
    "{user1} lanza un {item} en la dirección general de {user2} ",
    "{user1} comienza a abofetear a {user2} con un {item}.",
    "{user1} fija a {user2} y lo {hits} repetidamente con un {item}.",
    "{user1} gagarra un {item} y {hits} a {user2} con eso.",
    "{user1} ata a {user2} a una silla y {throws} un {item} hacia ellos.",
    "{user1} dio un empujón amistoso para ayudar a {user2} para aprender a nadar en la lava.",
    "{user1} intimidó a {user2}.",
    "Nyaan se comió la pierna de {user2}. *nomnomnom*",
    "{user1} {throws} una bola maestra a {user2},  la resistencia es inútil.",
    "{user1} golpea a {user2} con un rayo de acción...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} golpes a {user2} con {item}.",
    "Ronda 2!..Listos? ... PELEEN!!",
    "Buzz Lightyear lanzará a {user2} al infinito y más allá.",
    "{user2} comió un murciélago y descubrió una nueva enfermedad.",
    "{user1} dobló a {user2} en un avión de papel",
    "{user1} le sirvió a {user2} un poco de sopa de murciélago.",
    "{user2} fue enviado a su hogar, el planeta de los simios.",
    "{user1} echó a {user2} de un tren en movimiento.",
    "{user2} acaba de matar al perro de John Wick.",
    "{user1} realizó un hechizo Avada Kadavra en {user2}.",
    "{user1} sometió a {user2} a un horno de fuego.",
    "Sakura Haruno acaba de volverse más útil que {user2}.",
    "{user1} desconectó el soporte vital de {user2}.",
    "{user1} subscribió a {user2} a 5 años de mala conexión a Internet..",
    "¿Sabes qué es peor que las bromas de papá? {user2}!",
    "{user1} tomó todas las galletas de {user2}.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} perdió su pieza de carrera!",  # No game no life reference
    "Cállate {user2}, sólo eres {user2}.",  # No game no life reference
    "{user1} golpea a {user2} con Aka si anse!",  # No game no life reference
    "@NeoTheKitty araña a {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu se come a {user2}",  # Dbz
    "Goblin slayer mata a {user2}",  # Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} le da palmaditas en la cabeza a {user2}",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus a la cabeza de {user2}*",
    "*{user1} arruina la cabeza de {user2}*",
    "*{user1} frota intensamente la cabeza de {user2}*",
    "*La waifu de {user2} acaricia su cabeza*",
    "*{user2} recibe palmaditas en la cabeza gratis*",
    "¡Nada de palmaditas para {user2}!",
    "¡Oh, no! Estamos todos sin palmaditas.",
    "¡Esta es una zona designada sin palmaditas!",
    "¡Nada de palmaditas para {user2}!",
    "{user1} mima a {user2} con palmaditas en la cabeza!",
    "{user2} recibe palmaditas gratis!",
    "{user1} le da palmaditas en la cabeza a {user2} mientras le da una almohada en el regazo",
    "{user1} acaricia agresivamente a {user2}",
    "{user1} acaricia suavemente la cabeza de {user2}",
    "Pat, pat, pat, pat",
    "{user2} no pudo escapar de las palmaditas en la cabeza de {user1}",
    "{user2}.exe ha dejado de funcionar",
    "{user1} frota {user2} en el cuello",
    "Debes... exprimir... dando palmaditas la cabeza",
    "{user1} acaricia la cabeza de {user2} con una palmada",
    "{user1} palmea la cabeza de {user2} inesperadamente",
    "{user1} le da palmaditas a {user2} con su consentimiento, ¿Tal vez?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} toca la cabeza de {user2} a toda hora",
    "{user1} frota el vientre de {user2}",
    "{user1} palmea a {user2} amistosamente",
    "{user2} usa palmaditas en la cabeza? O KAWAII KOTO",
    "*palmaditasenlacabeza.gif se intensifica para {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = ("ᴇsᴛᴏʏ ᴠɪᴠᴏ ʙʙ! 🖤",)

ITEMS = (
    "sartén de hierro fundido",
    "miau enojado",
    "bate de cricket",
    "bastón de madera",
    "pala",
    "tostadora",
    "libro",
    "laptop",
    "pollo de goma",
    "murciélago con púas",
    "rock pesado",
    "trozo de tierra",
    "tonelada de ladrillos",
    "doble rasengan",
    "bomba espiritual",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "kat volador esférico",
)

THROW = (
    "lanzó",
    "arrojó",
    "madreó",
    "tiró",
)

HIT = (
    "golpeó",
    "aporreó",
    "aabofeteó",
    "manoteó",
    "lapeó",
    "palmeó",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 Como yo lo veo, sí.",
    "🟡 Pregunta de nuevo más tarde.",
    "🟡 Mejor no decirte ahora.",
    "🟡 No se puede predecir ahora.",
    "🟡 Concéntrate y pregunta otra vez.",
    "🟡 no cuentes con eso.",
    "🟢 Es cierto.",
    "🟢 Es decididamente así.",
    "🟢 Más probable.",
    "🔴 Mi respuesta es no.",
    "🔴 Mis fuentes dicen que no.",
    "🔴 Perspectiva no tan buena.",
    "🟢 Perspectiva buena.",
    "🟡 Respuesta confusa, intenta otra vez.",
    "🟢 Las señales apuntan a que sí.",
    "🔴 Muy dudoso.",
    "🟢 Sin duda.",
    "🟢 Si.",
    "🟢 Si – definitivamente.",
    "🟢 Puedes confiar en ello.",
]

DECIDE = ("Si.", "No.", "Tal vez.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "Me quedé sin mesas, pediré más.",
    "Ve a trabajar en lugar de voltear mesas.",
)
